CREATE TABLE [dbo].[FINANCIAL_ITEM]
(
	[PARTNER_ID] DECIMAL NOT NULL, 
    [DATE] DATE NOT NULL, 
    [AMOUNT] DECIMAL NOT NULL, 
    [ID] INT NOT NULL IDENTITY, 
    CONSTRAINT [PK_FINANCIAL_ITEM] PRIMARY KEY ([ID]), 
    CONSTRAINT [FK_FINANCIAL_ITEM_ToPARTNER] FOREIGN KEY ([PARTNER_ID]) REFERENCES [PARTNER]([PARTNER_ID])
)
