CREATE TABLE [dbo].[PARTNER]
(
	[PARTNER_ID] DECIMAL NOT NULL PRIMARY KEY IDENTITY, 
    [PARTNER_NAME] NVARCHAR(50) NOT NULL, 
    [PARENT_PARTNER_ID] DECIMAL NOT NULL DEFAULT 1, 
    [FEE_PERCENT] DECIMAL(20, 1) NOT NULL 
)
